version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - pgvector
      - ollama
    volumes:
      - .:/app

  pgvector:
    image: phidata/pgvector:16
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5532:5432"

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "your_port:your_port"
    volumes:
      - ollama_data:/var/lib/ollama  # Assuming Ollama needs persistent data

volumes:
  pgdata:
  ollama_data: