FROM python:3.12

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY requirements_fastapi.txt .

RUN pip install --no-cache-dir -r requirements_fastapi.txt
RUN pip install celery redis

COPY . .

CMD ["python", "backend.py"]