FROM python:3.12

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY requirements_fastapi.txt .

RUN pip install --no-cache-dir -r requirements_fastapi.txt

COPY backend.py .
COPY .env .

CMD ["python", "backend.py"]