"""Initial migration

Revision ID: 3e624f7236cb
Revises: 
Create Date: 2024-09-17 18:30:06.418727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e624f7236cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_os_runs')
    op.create_foreign_key(None, 'dora_metric_snapshots', 'devops_projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'dora_metric_snapshots', 'devops_teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'dora_metrics', 'devops_projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'dora_metrics', 'devops_teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dora_metrics', type_='foreignkey')
    op.drop_constraint(None, 'dora_metrics', type_='foreignkey')
    op.drop_constraint(None, 'dora_metric_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'dora_metric_snapshots', type_='foreignkey')
    op.create_table('llm_os_runs',
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('run_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('llm', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assistant_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('run_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('task_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('run_id', name='llm_os_runs_pkey')
    )
    # ### end Alembic commands ###
