name: Comprehensive Deployment Record Workflow

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'Deployment Status'
        required: true
        default: 'Success'
        type: choice
        options:
        - Success
        - Failure
        - In Progress
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'Production'
        type: choice
        options:
        - Production
        - Staging
        - Development
      version:
        description: 'Deployment Version'
        required: true
        type: string
      associated_work_items:
        description: 'Associated Work Item IDs (comma-separated)'
        required: false
        type: string

jobs:
  record-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This fetches all history for all branches and tags

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time

    - name: Calculate deployment duration
      id: deployment-duration
      run: |
        START_TIME="${{ steps.current-time.outputs.epoch }}"
        # Simulate a deployment time (e.g., 5 minutes)
        sleep 300
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "::set-output name=duration::$DURATION"
        echo "::set-output name=end_time::$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")"

    - name: Determine deployment frequency
      id: deployment-frequency
      run: |
        DEPLOYMENTS_LAST_DAY=$(git log --since="1 day ago" --grep="Deployment Record" --oneline | wc -l)
        if [ $DEPLOYMENTS_LAST_DAY -gt 1 ]; then
          FREQUENCY="Multiple deploys per day"
        elif [ $DEPLOYMENTS_LAST_DAY -eq 1 ]; then
          FREQUENCY="Once per day"
        else
          FREQUENCY="Less than once per day"
        fi
        echo "::set-output name=frequency::$FREQUENCY"

    - name: Record Deployment in Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      run: |
        urlencode() {
          local length="${#1}"
          for (( i = 0; i < length; i++ )); do
            local c="${1:i:1}"
            case $c in
              [a-zA-Z0-9.~_-]) printf "$c" ;;
              *) printf '%%%02X' "'$c" ;;
            esac
          done
        }

        ENCODED_ORG=$(urlencode "${AZURE_DEVOPS_ORG}")
        ENCODED_PROJECT=$(urlencode "${AZURE_DEVOPS_PROJECT}")
        URL="https://dev.azure.com/${ENCODED_ORG}/${ENCODED_PROJECT}/_apis/wit/workitems/\$Deployment?api-version=6.0"
        echo "Constructed URL: $URL"

        # Construct JSON data with all fields
        JSON_DATA=$(cat << EOF
        [
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStatus",
            "value": "${{ github.event.inputs.deployment_status }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentTimestamp",
            "value": "${{ steps.current-time.outputs.rfc3339 }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentID",
            "value": "${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/System.State",
            "value": "New"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStartTime",
            "value": "${{ steps.current-time.outputs.rfc3339 }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentEndTime",
            "value": "${{ steps.deployment-duration.outputs.end_time }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.Environment",
            "value": "${{ github.event.inputs.environment }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.Version",
            "value": "${{ github.event.inputs.version }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentDuration",
            "value": ${{ steps.deployment-duration.outputs.duration }}
          },
          {
            "op": "add",
            "path": "/fields/Custom.TimeToRestore",
            "value": 0
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentFrequency",
            "value": "${{ steps.deployment-frequency.outputs.frequency }}"
          },
          {
            "op": "add",
            "path": "/fields/System.Title",
            "value": "Deployment Record - ${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeployedWorkItems",
            "value": "${{ github.event.inputs.associated_work_items }}"
          }
        ]
        EOF
        )

        echo "JSON Data:"
        echo "$JSON_DATA"

        # Execute the curl command with verbose output
        RESPONSE=$(curl -v -s -X POST "${URL}" \
          -H "Content-Type: application/json-patch+json" \
          -H "Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)" \
          -d "$JSON_DATA" 2>&1)

        echo "Full Curl Response:"
        echo "$RESPONSE"

        # Extract the HTTP status code
        HTTP_STATUS=$(echo "$RESPONSE" | grep -i "< HTTP" | awk '{print $3}')
        echo "HTTP Status Code: $HTTP_STATUS"

        # Check if the API call was successful
        if [[ "$HTTP_STATUS" =~ ^2 ]]; then
          echo "Deployment record created successfully"
          WORK_ITEM_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | cut -d':' -f2)
          echo "Created Work Item ID: $WORK_ITEM_ID"

          # Link the deployment work item to the associated work items
          if [ ! -z "${{ github.event.inputs.associated_work_items }}" ]; then
            IFS=',' read -ra WORK_ITEM_ARRAY <<< "${{ github.event.inputs.associated_work_items }}"
            for ITEM_ID in "${WORK_ITEM_ARRAY[@]}"; do
              LINK_JSON=$(cat << EOF
              [
                {
                  "op": "add",
                  "path": "/relations/-",
                  "value": {
                    "rel": "System.LinkTypes.Related",
                    "url": "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/wit/workItems/${ITEM_ID}",
                    "attributes": {
                      "comment": "Associated with deployment"
                    }
                  }
                }
              ]
              EOF
              )

              curl -s -X PATCH "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/wit/workitems/${WORK_ITEM_ID}?api-version=6.0" \
                -H "Content-Type: application/json-patch+json" \
                -H "Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)" \
                -d "$LINK_JSON"
            done
          fi
        else
          echo "Failed to create deployment record"
          ERROR_MESSAGE=$(echo "$RESPONSE" | grep -o '"message":"[^"]*' | cut -d'"' -f4)
          echo "Error Message: $ERROR_MESSAGE"
          if echo "$ERROR_MESSAGE" | grep -q "TF401324"; then
            echo "You might not have permission to create work items or use certain fields. Please check your PAT permissions."
          elif echo "$ERROR_MESSAGE" | grep -q "TF51535"; then
            FIELD_NAME=$(echo "$ERROR_MESSAGE" | grep -oP "TF51535: Cannot find field \K\S+")
            echo "The field $FIELD_NAME is missing or not accessible. Please check if it exists in your process or if you have permission to access it."
          fi
          exit 1
        fi

    - name: Debug Output
      run: |
        echo "Deployment ID: ${{ github.run_number }}"
        echo "Deployment Status: ${{ github.event.inputs.deployment_status }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Version: ${{ github.event.inputs.version }}"
        echo "Timestamp: ${{ steps.current-time.outputs.rfc3339 }}"
        echo "Duration: ${{ steps.deployment-duration.outputs.duration }} seconds"
        echo "Frequency: ${{ steps.deployment-frequency.outputs.frequency }}"
        echo "Associated Work Items: ${{ github.event.inputs.associated_work_items }}"