name: Isolated Curl Command Debug

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'Deployment Status'
        required: true
        default: 'Success'
        type: choice
        options:
        - Success
        - Failure
        - In Progress

jobs:
  debug-curl-command:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time

    - name: Debug Curl Command
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      run: |
        # Define variables
        BASE_URL="https://dev.azure.com"
        API_PATH="_apis/wit/workitems/\$Deployment"
        QUERY_PARAMS="api-version=6.0"
        CONTENT_TYPE="application/json-patch+json"
        AUTH_HEADER="Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)"
        
        # Construct full URL
        FULL_URL="${BASE_URL}/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/${API_PATH}?${QUERY_PARAMS}"
        
        # Print debug information
        echo "Base URL: ${BASE_URL}"
        echo "Organization: ${AZURE_DEVOPS_ORG}"
        echo "Project: ${AZURE_DEVOPS_PROJECT}"
        echo "API Path: ${API_PATH}"
        echo "Query Parameters: ${QUERY_PARAMS}"
        echo "Full URL: ${FULL_URL}"
        
        # Construct JSON data
        JSON_DATA=$(cat << EOF
        [
          {
            "op": "add",
            "path": "/fields/System.Title",
            "value": "Deployment ${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/System.State",
            "value": "Completed"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentID",
            "value": "${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStatus",
            "value": "${{ github.event.inputs.deployment_status }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentTimestamp",
            "value": "${{ steps.current-time.outputs.time }}"
          }
        ]
        EOF
        )
        
        echo "JSON Data:"
        echo "${JSON_DATA}"
        
        # Execute curl command
        echo "Executing curl command..."
        curl_output=$(curl -v -X POST "${FULL_URL}" \
          -H "Content-Type: ${CONTENT_TYPE}" \
          -H "${AUTH_HEADER}" \
          -d "${JSON_DATA}" 2>&1)
        curl_exit_code=$?
        
        echo "Curl Exit Code: ${curl_exit_code}"
        echo "Curl Output:"
        echo "${curl_output}"
        
        if [ ${curl_exit_code} -ne 0 ]; then
          echo "Curl command failed"
          exit 1
        else
          echo "Curl command succeeded"
        fi

    - name: Debug Output
      run: |
        echo "Deployment ID: ${{ github.run_number }}"
        echo "Deployment Status: ${{ github.event.inputs.deployment_status }}"
        echo "Timestamp: ${{ steps.current-time.outputs.time }}"