name: Test Record Deployment

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'Deployment Status'
        required: true
        default: 'Success'
        type: choice
        options:
        - Success
        - Failure
        - In Progress

jobs:
  test-record-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time

    - name: Record Deployment in Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      run: |
        curl -X POST "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/wit/workitems/\$Deployment?api-version=6.0" \
        -H "Content-Type: application/json-patch+json" \
        -H "Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)" \
        -d '[
          {
            "op": "add",
            "path": "/fields/System.Title",
            "value": "Test Deployment ${{ github.sha }}"
          },
          {
            "op": "add",
            "path": "/fields/System.State",
            "value": "Completed"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentID",
            "value": "${{ github.sha }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStatus",
            "value": "${{ github.event.inputs.deployment_status }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentTimestamp",
            "value": "${{ steps.current-time.outputs.time }}"
          }
        ]'

    - name: Check curl exit status
      run: |
        if [ $? -eq 0 ]; then
          echo "Curl command succeeded"
        else
          echo "Curl command failed"
          exit 1
        fi