name: Debug Azure DevOps Integration

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'Deployment Status'
        required: true
        default: 'Success'
        type: choice
        options:
        - Success
        - Failure
        - In Progress

jobs:
  test-record-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time

    - name: Prepare and execute curl command
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      run: |
        # Debug: Print environment variable names (not values)
        echo "Environment variables set:"
        echo "AZURE_DEVOPS_ORG is set: $([[ -n $AZURE_DEVOPS_ORG ]] && echo 'Yes' || echo 'No')"
        echo "AZURE_DEVOPS_PROJECT is set: $([[ -n $AZURE_DEVOPS_PROJECT ]] && echo 'Yes' || echo 'No')"
        echo "AZURE_DEVOPS_PAT is set: $([[ -n $AZURE_DEVOPS_PAT ]] && echo 'Yes' || echo 'No')"
        
        # Construct URL
        URL="https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/wit/workitems/\$Deployment?api-version=6.0"
        echo "Constructed URL (with placeholders): $URL"
        
        # Construct auth header
        AUTH_HEADER="Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)"
        echo "Auth header constructed (not shown for security)"
        
        # Construct JSON data
        JSON_DATA=$(cat << EOF
        [
          {
            "op": "add",
            "path": "/fields/System.Title",
            "value": "Test Deployment ${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/System.State",
            "value": "Completed"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentID",
            "value": ${{ github.run_number }}
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStatus",
            "value": "${{ github.event.inputs.deployment_status }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentTimestamp",
            "value": "${{ steps.current-time.outputs.time }}"
          }
        ]
        EOF
        )
        echo "JSON data constructed:"
        echo "$JSON_DATA"
        
        # Execute curl command
        echo "Executing curl command..."
        curl -v -X POST "$URL" \
          -H "Content-Type: application/json-patch+json" \
          -H "$AUTH_HEADER" \
          -d "$JSON_DATA"
        
        # Check curl exit status
        if [ $? -eq 0 ]; then
          echo "Curl command succeeded"
        else
          echo "Curl command failed"
          exit 1
        fi

    - name: Debug Output
      run: |
        echo "Deployment ID: ${{ github.run_number }}"
        echo "Deployment Status: ${{ github.event.inputs.deployment_status }}"
        echo "Timestamp: ${{ steps.current-time.outputs.time }}"