name: Enhanced Debug Azure DevOps Integration

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'Deployment Status'
        required: true
        default: 'Success'
        type: choice
        options:
        - Success
        - Failure
        - In Progress

jobs:
  record-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time

    - name: Execute Azure DevOps API call
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
      run: |
        set -x  # Enable debug mode

        # Construct URL with escaped $
        URL="https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/wit/workitems/\$Deployment?api-version=6.0"
        echo "Constructed URL (with placeholders): $URL"
        
        # Construct auth header
        AUTH_HEADER="Authorization: Basic $(echo -n :${AZURE_DEVOPS_PAT} | base64)"
        echo "Auth header constructed (not shown for security)"
        
        # Construct JSON data
        JSON_DATA=$(cat << EOF
        [
          {
            "op": "add",
            "path": "/fields/System.Title",
            "value": "Deployment ${{ github.run_number }}"
          },
          {
            "op": "add",
            "path": "/fields/System.State",
            "value": "Completed"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentID",
            "value": ${{ github.run_number }}
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentStatus",
            "value": "${{ github.event.inputs.deployment_status }}"
          },
          {
            "op": "add",
            "path": "/fields/Custom.DeploymentTimestamp",
            "value": "${{ steps.current-time.outputs.time }}"
          }
        ]
        EOF
        )
        echo "JSON data constructed:"
        echo "$JSON_DATA"
        
        # Execute curl command with full verbose output
        echo "Executing curl command..."
        set +x  # Disable debug mode to prevent exposing the PAT
        RESPONSE=$(curl -v -s -w "\n%{http_code}" -X POST "$URL" \
          -H "Content-Type: application/json-patch+json" \
          -H "$AUTH_HEADER" \
          -d "$JSON_DATA" 2>&1)
        CURL_EXIT_CODE=$?
        set -x  # Re-enable debug mode
        
        echo "Curl exit code: $CURL_EXIT_CODE"
        echo "Full curl response:"
        echo "$RESPONSE"
        
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')
        
        echo "HTTP Status: $HTTP_STATUS"
        echo "Response Body: $BODY"
        
        # Check if curl was successful
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Curl command failed with exit code $CURL_EXIT_CODE"
          exit 1
        fi
        
        # Check if the request was successful
        if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
          echo "Azure DevOps API call succeeded"
        else
          echo "Azure DevOps API call failed with status $HTTP_STATUS"
          exit 1
        fi

    - name: Debug Output
      run: |
        echo "Deployment ID: ${{ github.run_number }}"
        echo "Deployment Status: ${{ github.event.inputs.deployment_status }}"
        echo "Timestamp: ${{ steps.current-time.outputs.time }}"